app:
  server:
    domain: localhost
    hosts: http://${app.server.domain}:3000, http://localhost:8080
  jwt:
    secret: antte
    maxAge: 60602430
  filePrePath: ${user.dir}/upload

spring:
  profiles:
    active: local
  web:
    resources:
      static-locations: file:${app.filePrePath},  classpath:/resources/static
server:
  error:
    include-message: always
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/sns
    username: antte
    password: antte
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_batch_fetch_size: 1000
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      log-file: logs/spy.log
logging:
  file:
    path: logs
#  level:
#    root: trace